from random import shuffle

from classes import City, Edge, Colors, Destination


def create_board():
    """
    Initializes the entirety of the game state.
    """
    # Initialize all cities.
    cities = {"Atlanta": City(name="Atlanta", abbreviation="At"),
              "Boston": City("Boston", "Bo"),
              "Calgary": City("Calgary", "Ca"),
              "Charleston": City("Charleston", "Ch"),
              "Chicago": City("Chicago", "Cc"),
              "Dallas": City("Dallas", "Da"),
              "Denver": City("Denver", "De"),
              "Duluth": City("Duluth", "Du"),
              "El Paso": City("El Paso", "Ep"),
              "Helena": City("Helena", "He"),
              "Houston": City("Houston", "Ho"),
              "Kansas City": City("Kansas City", "Kc"),
              "Las Vegas": City("Las Vegas", "Lv"),
              "Little Rock": City("Little Rock", "Lr"),
              "Los Angeles": City("Los Angeles", "La"),
              "Miami": City("Miami", "Mi"),
              "Montreal": City("Montreal", "Mo"),
              "Nashville": City("Nashville", "Na"),
              "New Orleans": City("New Orleans", "No"),
              "New York": City("New York", "Ny"),
              "Oklahoma City": City("Oklahoma City", "Oc"),
              "Omaha": City("Omaha", "Om"),
              "Phoenix": City("Phoenix", "Ph"),
              "Pittsburgh": City("Pittsburgh", "Pi"),
              "Portland": City("Portland", "Po"),
              "Raleigh": City("Raleigh", "Ra"),
              "Saint Louis": City("Saint Louis", "Sl"),
              "Salt Lake City": City("Salt Lake City", "Slc"),
              "San Francisco": City("San Francisco", "Sf"),
              "Santa Fe": City("Santa Fe", "Saf"),
              "Sault St. Marie": City("Sault St. Marie", "Ssm"),
              "Seattle": City("Seattle", "Se"),
              "Toronto": City("Toronto", "To"),
              "Vancouver": City("Vancouver", "Va"),
              "Washington DC": City("Washington DC", "Wa"),
              "Winnipeg": City("Winnipeg", "Wi"),
              }

    # Create all the edges between cities.
    edges = [
        Edge(cities["Atlanta"], cities["Charleston"], cost=2, color=Colors.none),
        Edge(cities["Atlanta"], cities["Miami"], cost=5, color=Colors.blue),
        Edge(cities["Atlanta"], cities["Nashville"], cost=1, color=Colors.none),
        Edge(cities["Atlanta"], cities["New Orleans"], cost=4, color=Colors.orange),
        Edge(cities["Atlanta"], cities["New Orleans"], cost=4, color=Colors.yellow),
        Edge(cities["Atlanta"], cities["Raleigh"], cost=2, color=Colors.none),
        Edge(cities["Boston"], cities["Montreal"], cost=2, color=Colors.none),
        Edge(cities["Boston"], cities["Montreal"], cost=2, color=Colors.none),
        Edge(cities["Boston"], cities["New York"], cost=2, color=Colors.red),
        Edge(cities["Boston"], cities["New York"], cost=2, color=Colors.yellow),
        Edge(cities["Calgary"], cities["Helena"], cost=4, color=Colors.none),
        Edge(cities["Calgary"], cities["Seattle"], cost=4, color=Colors.none),
        Edge(cities["Calgary"], cities["Vancouver"], cost=3, color=Colors.none),
        Edge(cities["Calgary"], cities["Winnipeg"], cost=6, color=Colors.white),
        Edge(cities["Charleston"], cities["Miami"], cost=4, color=Colors.pink),
        Edge(cities["Charleston"], cities["Raleigh"], cost=1, color=Colors.none),
        Edge(cities["Chicago"], cities["Duluth"], cost=3, color=Colors.red),
        Edge(cities["Chicago"], cities["Omaha"], cost=4, color=Colors.blue),
        Edge(cities["Chicago"], cities["Pittsburgh"], cost=3, color=Colors.black),
        Edge(cities["Chicago"], cities["Pittsburgh"], cost=3, color=Colors.orange),
        Edge(cities["Chicago"], cities["Saint Louis"], cost=2, color=Colors.green),
        Edge(cities["Chicago"], cities["Saint Louis"], cost=2, color=Colors.white),
        Edge(cities["Chicago"], cities["Toronto"], cost=4, color=Colors.white),
        Edge(cities["Dallas"], cities["El Paso"], cost=4, color=Colors.red),
        Edge(cities["Dallas"], cities["Houston"], cost=1, color=Colors.none),
        Edge(cities["Dallas"], cities["Houston"], cost=1, color=Colors.none),
        Edge(cities["Dallas"], cities["Little Rock"], cost=2, color=Colors.none),
        Edge(cities["Dallas"], cities["Oklahoma City"], cost=2, color=Colors.none),
        Edge(cities["Dallas"], cities["Oklahoma City"], cost=2, color=Colors.none),
        Edge(cities["Denver"], cities["Helena"], cost=4, color=Colors.green),
        Edge(cities["Denver"], cities["Kansas City"], cost=4, color=Colors.black),
        Edge(cities["Denver"], cities["Kansas City"], cost=4, color=Colors.orange),
        Edge(cities["Denver"], cities["Oklahoma City"], cost=4, color=Colors.red),
        Edge(cities["Denver"], cities["Omaha"], cost=4, color=Colors.pink),
        Edge(cities["Denver"], cities["Phoenix"], cost=4, color=Colors.white),
        Edge(cities["Denver"], cities["Salt Lake City"], cost=3, color=Colors.red),
        Edge(cities["Denver"], cities["Salt Lake City"], cost=3, color=Colors.yellow),
        Edge(cities["Denver"], cities["Santa Fe"], cost=2, color=Colors.none),
        Edge(cities["Duluth"], cities["Helena"], cost=6, color=Colors.orange),
        Edge(cities["Duluth"], cities["Omaha"], cost=2, color=Colors.none),
        Edge(cities["Duluth"], cities["Omaha"], cost=2, color=Colors.none),
        Edge(cities["Duluth"], cities["Sault St. Marie"], cost=3, color=Colors.none),
        Edge(cities["Duluth"], cities["Toronto"], cost=6, color=Colors.pink),
        Edge(cities["Duluth"], cities["Winnipeg"], cost=4, color=Colors.black),
        Edge(cities["El Paso"], cities["Houston"], cost=6, color=Colors.green),
        Edge(cities["El Paso"], cities["Los Angeles"], cost=6, color=Colors.black),
        Edge(cities["El Paso"], cities["Oklahoma City"], cost=5, color=Colors.yellow),
        Edge(cities["El Paso"], cities["Phoenix"], cost=3, color=Colors.none),
        Edge(cities["El Paso"], cities["Santa Fe"], cost=2, color=Colors.none),
        Edge(cities["Helena"], cities["Calgary"], cost=4, color=Colors.none),
        Edge(cities["Helena"], cities["Omaha"], cost=5, color=Colors.red),
        Edge(cities["Helena"], cities["Seattle"], cost=6, color=Colors.yellow),
        Edge(cities["Helena"], cities["Winnipeg"], cost=4, color=Colors.blue),
        Edge(cities["Houston"], cities["New Orleans"], cost=2, color=Colors.none),
        Edge(cities["Kansas City"], cities["Oklahoma City"], cost=2, color=Colors.none),
        Edge(cities["Kansas City"], cities["Oklahoma City"], cost=2, color=Colors.none),
        Edge(cities["Kansas City"], cities["Omaha"], cost=1, color=Colors.none),
        Edge(cities["Kansas City"], cities["Omaha"], cost=1, color=Colors.none),
        Edge(cities["Kansas City"], cities["Saint Louis"], cost=2, color=Colors.blue),
        Edge(cities["Kansas City"], cities["Saint Louis"], cost=2, color=Colors.pink),
        Edge(cities["Las Vegas"], cities["Los Angeles"], cost=2, color=Colors.none),
        Edge(cities["Las Vegas"], cities["Salt Lake City"], cost=3, color=Colors.orange),
        Edge(cities["Little Rock"], cities["Nashville"], cost=3, color=Colors.white),
        Edge(cities["Little Rock"], cities["New Orleans"], cost=3, color=Colors.green),
        Edge(cities["Little Rock"], cities["Oklahoma City"], cost=2, color=Colors.none),
        Edge(cities["Little Rock"], cities["Saint Louis"], cost=2, color=Colors.none),
        Edge(cities["Los Angeles"], cities["Phoenix"], cost=2, color=Colors.black),
        Edge(cities["Los Angeles"], cities["San Francisco"], cost=3, color=Colors.pink),
        Edge(cities["Los Angeles"], cities["San Francisco"], cost=3, color=Colors.yellow),
        Edge(cities["Miami"], cities["New Orleans"], cost=6, color=Colors.red),
        Edge(cities["Montreal"], cities["New York"], cost=3, color=Colors.blue),
        Edge(cities["Montreal"], cities["Sault St. Marie"], cost=5, color=Colors.black),
        Edge(cities["Montreal"], cities["Toronto"], cost=3, color=Colors.none),
        Edge(cities["Nashville"], cities["Pittsburgh"], cost=4, color=Colors.yellow),
        Edge(cities["Nashville"], cities["Raleigh"], cost=3, color=Colors.black),
        Edge(cities["Nashville"], cities["Saint Louis"], cost=2, color=Colors.none),
        Edge(cities["New York"], cities["Pittsburgh"], cost=2, color=Colors.green),
        Edge(cities["New York"], cities["Pittsburgh"], cost=2, color=Colors.white),
        Edge(cities["New York"], cities["Washington DC"], cost=2, color=Colors.black),
        Edge(cities["New York"], cities["Washington DC"], cost=2, color=Colors.orange),
        Edge(cities["Phoenix"], cities["Santa Fe"], cost=3, color=Colors.none),
        Edge(cities["Pittsburgh"], cities["Saint Louis"], cost=5, color=Colors.green),
        Edge(cities["Portland"], cities["Salt Lake City"], cost=6, color=Colors.blue),
        Edge(cities["Portland"], cities["San Francisco"], cost=5, color=Colors.green),
        Edge(cities["Portland"], cities["San Francisco"], cost=5, color=Colors.pink),
        Edge(cities["Portland"], cities["Seattle"], cost=1, color=Colors.none),
        Edge(cities["Portland"], cities["Seattle"], cost=1, color=Colors.none),
        Edge(cities["Raleigh"], cities["Washington DC"], cost=2, color=Colors.none),
        Edge(cities["Salt Lake City"], cities["San Francisco"], cost=5, color=Colors.orange),
        Edge(cities["Salt Lake City"], cities["San Francisco"], cost=5, color=Colors.white),
        Edge(cities["Sault St. Marie"], cities["Toronto"], cost=2, color=Colors.none),
        Edge(cities["Sault St. Marie"], cities["Winnipeg"], cost=6, color=Colors.none),
        Edge(cities["Seattle"], cities["Vancouver"], cost=1, color=Colors.none),
    ]

    # Convert cities to tuples.
    for key in cities:
        cities[key] = cities[key].to_tuple()

    # Initialize the deck to have 12 of each color and 14 wild cards (which are just cards colored "None").
    deck = [color for color in range(8)] * 12 + [8] * 14

    destinations = [
        Destination(cities["Dallas"], cities["New York"], 11),
        Destination(cities["Portland"], cities["Phoenix"], 11),
        Destination(cities["Vancouver"], cities["Santa Fe"], 13),
        Destination(cities["Seattle"], cities["New York"], 22),
        Destination(cities["Montreal"], cities["Atlanta"], 9),
        Destination(cities["Toronto"], cities["Miami"], 10),
        Destination(cities["Boston"], cities["Miami"], 12),
        Destination(cities["Los Angeles"], cities["Chicago"], 16),
        Destination(cities["Winnipeg"], cities["Houston"], 12),
        Destination(cities["Denver"], cities["El Paso"], 4),
        Destination(cities["Duluth"], cities["Houston"], 8),
        Destination(cities["San Francisco"], cities["Atlanta"], 17),
        Destination(cities["Denver"], cities["Pittsburgh"], 11),
        Destination(cities["Sault St. Marie"], cities["Nashville"], 8),
        Destination(cities["Winnipeg"], cities["Little Rock"], 11),
        Destination(cities["Duluth"], cities["El Paso"], 10),
        Destination(cities["Seattle"], cities["Los Angeles"], 9),
        Destination(cities["Helena"], cities["Los Angeles"], 8),
        Destination(cities["Kansas City"], cities["Houston"], 5),
        Destination(cities["Sault St. Marie"], cities["Oklahoma City"], 9),
        Destination(cities["Portland"], cities["Nashville"], 17),
        Destination(cities["Los Angeles"], cities["New York"], 21),
        Destination(cities["Chicago"], cities["Santa Fe"], 9),
        Destination(cities["Calgary"], cities["Phoenix"], 13),
        Destination(cities["Calgary"], cities["Salt Lake City"], 7),
        Destination(cities["Vancouver"], cities["Montreal"], 20),
        Destination(cities["Los Angeles"], cities["Miami"], 20),
        Destination(cities["Chicago"], cities["New Orleans"], 7),
        Destination(cities["New York"], cities["Atlanta"], 6),
        Destination(cities["Montreal"], cities["New Orleans"], 13)
    ]

    shuffle(destinations)
    shuffle(deck)

    # Create a dictionary for scoring.
    scoring = {1: 1,
               2: 2,
               3: 4,
               4: 7,
               5: 10,
               6: 15}

    return cities, edges, deck, destinations, scoring
